service: word-battle-service

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: []
    target: "node18"
    platform: "node"
    concurrency: 10

functions:
  app:
    handler: src/handler.app
    events:
      - http:
          path: /app
          method: post
